pattens_data_ABX3 = ['element_A', 'element_B', 'element_X', 'melting_A', 'boiling_A',
                'electronegativity_A', 'ionization_A', 'melting_B', 'boiling_B', 'electronegativity_B',
                'ionization_B',
                'Density_A', 'at.wt._A', 'BCCenergy_pa_A', 'BCCfermi_A', 'BCCvolume_pa_A', 'GSenergy_pa_A',
                'ICSDVolume_A',
                'covalentradius_A', 'IonizationEnergy(kJ / mol)_A', 'AtomicRadius(Å)_A',
                'ElectronAffinity(kJ / mol)_A',
                'At.Radius(angstroms)_A', 'AtomicVolume(cm³ / mol)_A', 'FirstIonizationPotential(V)_A',
                'SecondIonizationPotential(V)_A', 'ThirdIonizationPotential(V)_A',
                'CoeficientofThermalExpansion(10 ^ -6K - 1)_A', 'specificheatcapacity_A', 'thermalconductivity_A',
                'heatoffusion_A', 'HeatofVaporization_A', 'At.# _A', 'Density_B', 'at.wt._B', 'BCCenergy_pa_B',
                'BCCfermi_B', 'BCCvolume_pa_B', 'GSenergy_pa_B', 'ICSDVolume_B', 'covalentradius_B',
                'IonizationEnergy(kJ / mol)_B', 'AtomicRadius(Å)_B', 'ElectronAffinity(kJ / mol)_B',
                'At.Radius(angstroms)_B', 'AtomicVolume(cm³ / mol)_B', 'FirstIonizationPotential(V)_B',
                'SecondIonizationPotential(V)_B', 'ThirdIonizationPotential(V)_B',
                'CoeficientofThermalExpansion(10 ^ -6K - 1)_B', 'specificheatcapacity_B', 'thermalconductivity_B',
                'heatoffusion_B', 'HeatofVaporization_B', 'At.# _B', 'Density_X', 'at.wt._X', 'BCCenergy_pa_X',
                'BCCfermi_X', 'BCCvolume_pa_X', 'GSenergy_pa_X', 'ICSDVolume_X', 'covalentradius_X',
                'IonizationEnergy_X', 'AtomicRadius_X', 'ElectronAffinity_X', 'At.Radius(angstroms)_X',
                'AtomicVolume_X', 'FirstIonizationPotential_X', 'SecondIonizationPotential_X',
                'ThirdIonizationPotential_X', 'CoeficientofThermalExpansion_X', 'specificheatcapacity_X',
                'thermalconductivity_X', 'heatoffusion_X', 'HeatofVaporization_X', 'At.# _X',
                'melting_X', 'boiling_X', 'electronegativity_X', 'ionization_X', 'A_radius', 'B_radius', 'radius_X',
                 'formation energy per atom']

pattens_predict_ABX3 = ['element_A', 'element_B', 'element_X', 'melting_A', 'boiling_A',
                   'electronegativity_A', 'ionization_A', 'melting_B', 'boiling_B', 'electronegativity_B',
                   'ionization_B',
                   'Density_A', 'at.wt._A', 'BCCenergy_pa_A', 'BCCfermi_A', 'BCCvolume_pa_A', 'GSenergy_pa_A',
                   'ICSDVolume_A',
                   'covalentradius_A', 'IonizationEnergy(kJ / mol)_A', 'AtomicRadius(Å)_A',
                   'ElectronAffinity(kJ / mol)_A',
                   'At.Radius(angstroms)_A', 'AtomicVolume(cm³ / mol)_A', 'FirstIonizationPotential(V)_A',
                   'SecondIonizationPotential(V)_A', 'ThirdIonizationPotential(V)_A',
                   'CoeficientofThermalExpansion(10 ^ -6K - 1)_A', 'specificheatcapacity_A', 'thermalconductivity_A',
                   'heatoffusion_A', 'HeatofVaporization_A', 'At.# _A', 'Density_B', 'at.wt._B', 'BCCenergy_pa_B',
                   'BCCfermi_B', 'BCCvolume_pa_B', 'GSenergy_pa_B', 'ICSDVolume_B', 'covalentradius_B',
                   'IonizationEnergy(kJ / mol)_B', 'AtomicRadius(Å)_B', 'ElectronAffinity(kJ / mol)_B',
                   'At.Radius(angstroms)_B', 'AtomicVolume(cm³ / mol)_B', 'FirstIonizationPotential(V)_B',
                   'SecondIonizationPotential(V)_B', 'ThirdIonizationPotential(V)_B',
                   'CoeficientofThermalExpansion(10 ^ -6K - 1)_B', 'specificheatcapacity_B', 'thermalconductivity_B',
                   'heatoffusion_B', 'HeatofVaporization_B', 'At.# _B', 'Density_X', 'at.wt._X', 'BCCenergy_pa_X',
                   'BCCfermi_X', 'BCCvolume_pa_X', 'GSenergy_pa_X', 'ICSDVolume_X', 'covalentradius_X',
                   'IonizationEnergy_X', 'AtomicRadius_X', 'ElectronAffinity_X', 'At.Radius(angstroms)_X',
                   'AtomicVolume_X', 'FirstIonizationPotential_X', 'SecondIonizationPotential_X',
                   'ThirdIonizationPotential_X', 'CoeficientofThermalExpansion_X', 'specificheatcapacity_X',
                   'thermalconductivity_X', 'heatoffusion_X', 'HeatofVaporization_X', 'At.# _X',
                   'melting_X', 'boiling_X', 'electronegativity_X', 'ionization_X', 'A_radius', 'B_radius', 'radius_X',
                   ]

pattens_predict_A2BCX6 = ['A', 'B1', 'B2', 'X',  'melting_A', 'boiling_A',
                   'electronegativity_A', 'ionization_A', 'melting_B1', 'boiling_B1', 'electronegativity_B1',
                   'ionization_B1', 'melting_B2', 'boiling_B2', 'electronegativity_B2',
                   'ionization_B2',
                   'Density_A', 'at.wt._A', 'BCCenergy_pa_A', 'BCCfermi_A', 'BCCvolume_pa_A', 'GSenergy_pa_A',
                   'ICSDVolume_A',
                   'covalentradius_A', 'IonizationEnergy(kJ / mol)_A', 'AtomicRadius(Å)_A',
                   'ElectronAffinity(kJ / mol)_A',
                   'At.Radius(angstroms)_A', 'AtomicVolume(cm³ / mol)_A', 'FirstIonizationPotential(V)_A',
                   'SecondIonizationPotential(V)_A', 'ThirdIonizationPotential(V)_A',
                   'CoeficientofThermalExpansion(10 ^ -6K - 1)_A', 'specificheatcapacity_A', 'thermalconductivity_A',
                   'heatoffusion_A', 'HeatofVaporization_A', 'At.# _A', 'Density_B1', 'at.wt._B1', 'BCCenergy_pa_1B',
                   'BCCfermi_B1', 'BCCvolume_pa_B1', 'GSenergy_pa_B1', 'ICSDVolume_B1', 'covalentradius_B1',
                   'IonizationEnergy(kJ / mol)_B1', 'AtomicRadius(Å)_B1', 'ElectronAffinity(kJ / mol)_B1',
                   'At.Radius(angstroms)_B1', 'AtomicVolume(cm³ / mol)_B1', 'FirstIonizationPotential(V)_B1',
                   'SecondIonizationPotential(V)_B1', 'ThirdIonizationPotential(V)_B1',
                   'CoeficientofThermalExpansion(10 ^ -6K - 1)_B1', 'specificheatcapacity_B1', 'thermalconductivity_B1',
                   'heatoffusion_B1', 'HeatofVaporization_B1', 'At.# _B1', 'Density_B2', 'at.wt._B2', 'BCCenergy_pa_B2',
                   'BCCfermi_B2', 'BCCvolume_pa_B2', 'GSenergy_pa_B2', 'ICSDVolume_B2', 'covalentradius_B2',
                   'IonizationEnergy(kJ / mol)_B2', 'AtomicRadius(Å)_B2', 'ElectronAffinity(kJ / mol)_B2',
                   'At.Radius(angstroms)_B2', 'AtomicVolume(cm³ / mol)_B2', 'FirstIonizationPotential(V)_B2',
                   'SecondIonizationPotential(V)_B2', 'ThirdIonizationPotential(V)_B2',
                   'CoeficientofThermalExpansion(10 ^ -6K - 1)_B2', 'specificheatcapacity_B2', 'thermalconductivity_B2',
                   'heatoffusion_B2', 'HeatofVaporization_B2', 'At.# _B2', 'Density_X', 'at.wt._X', 'BCCenergy_pa_X',
                   'BCCfermi_X', 'BCCvolume_pa_X', 'GSenergy_pa_X', 'ICSDVolume_X', 'covalentradius_X',
                   'IonizationEnergy_X', 'AtomicRadius_X', 'ElectronAffinity_X', 'At.Radius(angstroms)_X',
                   'AtomicVolume_X', 'FirstIonizationPotential_X', 'SecondIonizationPotential_X',
                   'ThirdIonizationPotential_X', 'CoeficientofThermalExpansion_X', 'specificheatcapacity_X',
                   'thermalconductivity_X', 'heatoffusion_X', 'HeatofVaporization_X', 'At.# _X',
                   'melting_X', 'boiling_X', 'electronegativity_X', 'ionization_X', 'A_radius', 'B1_radius',
                   'B2_radius', 'X_radius',]

pattens_data_A2BCX6 = ['A', 'B1', 'B2', 'X',  'melting_A', 'boiling_A',
                'electronegativity_A', 'ionization_A', 'melting_B1', 'boiling_B1', 'electronegativity_B1',
                'ionization_B1', 'melting_B2', 'boiling_B2', 'electronegativity_B2',
                'ionization_B2',
                'Density_A', 'at.wt._A', 'BCCenergy_pa_A', 'BCCfermi_A', 'BCCvolume_pa_A', 'GSenergy_pa_A',
                'ICSDVolume_A',
                'covalentradius_A', 'IonizationEnergy(kJ / mol)_A', 'AtomicRadius(Å)_A',
                'ElectronAffinity(kJ / mol)_A',
                'At.Radius(angstroms)_A', 'AtomicVolume(cm³ / mol)_A', 'FirstIonizationPotential(V)_A',
                'SecondIonizationPotential(V)_A', 'ThirdIonizationPotential(V)_A',
                'CoeficientofThermalExpansion(10 ^ -6K - 1)_A', 'specificheatcapacity_A', 'thermalconductivity_A',
                'heatoffusion_A', 'HeatofVaporization_A', 'At.# _A', 'Density_B1', 'at.wt._B1', 'BCCenergy_pa_1B',
                'BCCfermi_B1', 'BCCvolume_pa_B1', 'GSenergy_pa_B1', 'ICSDVolume_B1', 'covalentradius_B1',
                'IonizationEnergy(kJ / mol)_B1', 'AtomicRadius(Å)_B1', 'ElectronAffinity(kJ / mol)_B1',
                'At.Radius(angstroms)_B1', 'AtomicVolume(cm³ / mol)_B1', 'FirstIonizationPotential(V)_B1',
                'SecondIonizationPotential(V)_B1', 'ThirdIonizationPotential(V)_B1',
                'CoeficientofThermalExpansion(10 ^ -6K - 1)_B1', 'specificheatcapacity_B1', 'thermalconductivity_B1',
                'heatoffusion_B1', 'HeatofVaporization_B1', 'At.# _B1', 'Density_B2', 'at.wt._B2', 'BCCenergy_pa_B2',
                'BCCfermi_B2', 'BCCvolume_pa_B2', 'GSenergy_pa_B2', 'ICSDVolume_B2', 'covalentradius_B2',
                'IonizationEnergy(kJ / mol)_B2', 'AtomicRadius(Å)_B2', 'ElectronAffinity(kJ / mol)_B2',
                'At.Radius(angstroms)_B2', 'AtomicVolume(cm³ / mol)_B2', 'FirstIonizationPotential(V)_B2',
                'SecondIonizationPotential(V)_B2', 'ThirdIonizationPotential(V)_B2',
                'CoeficientofThermalExpansion(10 ^ -6K - 1)_B2', 'specificheatcapacity_B2', 'thermalconductivity_B2',
                'heatoffusion_B2', 'HeatofVaporization_B2', 'At.# _B2', 'Density_X', 'at.wt._X', 'BCCenergy_pa_X',
                'BCCfermi_X', 'BCCvolume_pa_X', 'GSenergy_pa_X', 'ICSDVolume_X', 'covalentradius_X',
                'IonizationEnergy_X', 'AtomicRadius_X', 'ElectronAffinity_X', 'At.Radius(angstroms)_X',
                'AtomicVolume_X', 'FirstIonizationPotential_X', 'SecondIonizationPotential_X',
                'ThirdIonizationPotential_X', 'CoeficientofThermalExpansion_X', 'specificheatcapacity_X',
                'thermalconductivity_X', 'heatoffusion_X', 'HeatofVaporization_X', 'At.# _X',
                'melting_X', 'boiling_X', 'electronegativity_X', 'ionization_X', 'A_radius', 'B1_radius', 'B2_radius',
                'X_radius', 'formation energy per atom']
